UserDAO class complete
TheDariusz/UserDAO pull request #3
Opened 2020-12-29 22:32 UTC by TheDariusz

2020-12-31 14:08 UTC, Wertros requested changes
It's logically correct but your project does not compile when checking from either main or this branch. Make sure your project is always in "green" state so someone else can pick it up from this point. I suggest to get through my comments and think about some refactor.

2020-12-31 14:08 UTC, Wertros commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +      }
There should be a better way of checking if this record exists in db or not.
Either way if block can be removed simply return rs.next() and throw exception in the catch block.

2021-01-01 13:06 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/DBUtil.java
> +  public static final String DB_PASSWORD = "coderslab";
corrected

2021-01-01 13:06 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/DBUtil.java
> +    throw new IllegalStateException("Utility class!");
thx :)

2021-01-01 13:13 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/DBUtil.java
> +      e.printStackTrace();
resolved

2021-01-01 13:32 UTC, TheDariusz commented on src/main/resources/log4j2.xml
> +</Configuration>
Maven was used, not jar file.
 ```
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.14.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.14.0</version>
        </dependency>
```

2021-01-01 14:20 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +  private static final String PASSWORD_COL = "password";
resolved

2021-01-01 14:22 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +    if (emailAlreadyExists(user.getId(), user.getEmail())) {
resolved

2021-01-01 14:39 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +      return null;
resolved

2021-01-01 14:44 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +      }
Not really...
"When a Statement object is closed, its current ResultSet object, if one exists, is also closed"
[https://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html](https://docs.oracle.com/javase/6/docs/api/java/sql/Statement.html)

2021-01-01 14:47 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +      return null;
I don't understand why I should throw my own exception in SQLException handler?

2021-01-01 14:48 UTC, TheDariusz commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +  }
resolved

2021-01-02 01:20 UTC, Wertros commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +      }
From the javadocs:

When a Statement object is closed, its current ResultSet object, if one exists, is also closed.

However, the javadocs are not very clear on whether the Statement and ResultSet are closed when you close the underlying Connection. They simply state that closing a Connection:

Releases this Connection object's database and JDBC resources immediately instead of waiting for them to be automatically released.

In my opinion, always explicitly close ResultSets, Statements and Connections when you are finished with them as the implementation of close could vary between database drivers.

2021-01-02 01:20 UTC, Wertros commented on src/main/java/pl/coderslab/workshop2/UserDAO.java
> +      }
I will leave this up to you :)

2021-01-02 01:21 UTC, Wertros approved these changes

2021-01-02 01:23 UTC, Wertros commented
Good job ! You can merge your changes with master but you may also want to have a look at my PR: https://github.com/TheDariusz/UserDAO/pull/4 

If you want to check it i recommend you to switch directly to my branch from intellij

2021-01-06 13:12 UTC, merged